name: Docker Compose test

on:
  push:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yaml'
      - '.github/workflows/docker_test.yaml'
      - 'wsgi.py'
  workflow_dispatch:

jobs:
  docker_test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Compose Build & Run
        run: docker-compose up -d --build
      - name: Run Tests
        run: docker compose exec flask pytest tests
      - name: Fetch artifacts
        run: |
          curl http://127.0.0.1:8080 -o index.html
          docker-compose logs > compose-logs.txt
          docker-compose down
      - uses: actions/upload-artifact@v4
        with:
          name: compose-artifacts
          path: |
            index.html
            compose-logs.txt
